### PR TITLE
Iterations support

### PR DESCRIPTION
**Pull request by ration**
Ability to pull headlines from iterations

### CODE REVIEW

**Comment by glittershark** [comment]
*hell* yeah!

**Comment by glittershark** [comment]
This has been on my list for ages, thank you. Also thanks for mirroring the existing style and architecture. Basically a perfect PR

**Comment by ration** [comment]
Thanks! Not perfect though, just noticed a copy paste error in the `org-clubhouse-iterations` description :) should be iteration-id not project-id

**Comment by glittershark** [comment]
ehh, it's only a docstring :) still pretty good

**Comment by glittershark** [comment]
12313582b8ddcc8ff59ea4d610e99c6c1b423eee

**Pull request merged**
